[directory]
truncation_length = 1
format = '[\[$path\]]($style)[$read_only]($read_only_style) '
read_only = '  '

[cmd_duration]
disabled = true

[line_break]
disabled = true

[python]
disabled = false
format = '[(\($virtualenv\) )]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[c]
format = 'via [$symbol($version(-$name) )]($style)'

[rust]
format = 'via [($version )]($style)'

