--local colors = {
--  blue   = '#80a0ff',
--  cyan   = '#79dac8',
--  black  = '#080808',
--  white  = '#c6c6c6',
--  red    = '#ff5189',
--  violet = '#d183e8',
--  grey   = '#303030',
--}
--
--require("onedark").setup{
--    lualine = {
--        transparent = true, -- lualine center bar transparency
--            },
--normal = {
--            a = { fg = colors.black, bg = colors.violet },
--            b = { fg = colors.white, bg = colors.grey },
--            c = { fg = colors.black, bg = colors.black },
--          },
--          insert = { a = { fg = colors.black, bg = colors.blue } },
--          visual = { a = { fg = colors.black, bg = colors.cyan } },
--          replace = { a = { fg = colors.black, bg = colors.red } },
--          inactive = {
--            a = { fg = colors.white, bg = colors.black },
--            b = { fg = colors.white, bg = colors.black },
--            c = { fg = colors.black, bg = colors.black },
--          },
--
--
--}
--require("onedark").load()
--
vim.g.neon_transparent = true
vim.cmd[[colorscheme neon]]
